### ISSUE TITLE
Srun error in cdo_remap.sh arise from remap.py of bedmap2

### ISSUE THREAD

**Issue by rersnow** [pism/pism-ais#5]
Hello everyone. I encountered a problem during the preprocessing step of bedmap2: after running remap.py,  the  cdo_remap.sh script was generated, and an error occurred when I used this shell script. The error is as follows:   cdo_remap.sh: Line 20: module: Command not found
                   cdo_remap.sh: Line 21: module: Command not found
                   srun: invalid option -'P'
                   srun: error: Invalid numeric value "cdo" for --ntasks.
                   srun: invalid option -'P'
                   srun: invalid option -'f'
                   srun: error: Invalid numeric value "cdo" for --ntasks.
I did not find an effective solution to this problem and was troubled by this problem for a long time. Could anyone help provide some advice? Thank you very much!

**Comment by talbrecht** [comment]
The remap.py skript generates a bash script (cdo_remap.sh), which can be submitted to a slurm batch queue (see comment in the header): 

```
# This script is specific for the PIK cluster, which uses SLURM for job scheduling. 
# and the module system.
```

If you want to run the remapping locally with cdo, you only need the part:

```
cdo genycon,/p/projects/tumble/albrecht/pism_input/data/cdo_remapgrids/pism_16km.nc /p/projects/tumble/albrecht/pism_input/data/bedmap2/bedmap2_1km_input.nc /p/projects/tumble/albrecht/pism_input/data/bedmap2/mapweights_16km.nc
```
etc.

You can also adjust the slurm skript to any other batch queue system, if you run into memory issues..

**Comment by rersnow** [comment]
Okay, I probably know how to do it. Thanks for your suggestions and help！

**Comment by m-kreuzer** [comment]
On the PIK cluster, we make use of the [Environment Modules](https://en.wikipedia.org/wiki/Environment_Modules_(software)). The commands 
> module load cdo
> module load nco

load `cdo` and `nco` into the current environment (include in `PATH`). If your machine does not use the module system, you need to comment this out and make sure that the necessary software is installed and available in your `PATH` variable. 

Hope this helps. Please let us know if the issue can be closed.

**Comment by rersnow** [comment]
Thank you very much for your help, it is very useful for me. 
My machine does not use the module system . So I have commented some statements in the script and  only recalculate locally with CDO.  
I will close this issure. Thank you again for your help!
