### ISSUE TITLE
RACMO2 data

### ISSUE THREAD

**Issue by rersnow** [pism/pism-ais#6]
When I tried to preprocess the RECMO data repeatedly and process the recom-ice2sea script, it prompted the lack of input Racmo data (HadCM3_c20_I2S_precip_Y.nc  HadCM3_c20_I2S_t2m_Y.nc ). 
Then I followed the script file instructions to find cited articles and related websites, but I still couldn't find any data to download.
If you have this data, could you provide it? Or tell me how to find and download this data? Thank you for your help!

**Comment by talbrecht** [comment]
Dear @rersnow ,
yes, those RACMO data (v.2.1, ANT27) are more than 6 years old and not public available. We would recommend to use the latest RACMO v2.3p2 data by Wessem et al., 2018 (racmo_wessem, ANT27/2), which are downloaded automatically from the iceclimate website (you find the link in the download script and in the config). See also the overview: https://www.projects.science.uu.nl/iceclimate/models/antarctica.php.
Best, Torsten

**Comment by rersnow** [comment]
Dear Torsten，
Okay, I got it. I will calculate according to RACMO v2.3 p2 data, thanks again for your help. 
I will close this issue later.
rersnow

**Comment by rersnow** [comment]
I'm sorry to bother you again. 
When running the racmo_wessem script, I found that the precipitation evaporation data(evap_RACMO2.3p2_yearly_ANT27_1979_2016.nc) is missing and it is not published at https://www.projects.science.uu.nl/iceclimate/publications/data/2018/
vwessem2018_tc/RACMO_Yearly/).

Where can I find this data? thank you very much

**Comment by rersnow** [comment]
I'm sorry to bother you again.
When running the racmo_wessem script, I found that the precipitation evaporation data(evap_RACMO2.3p2_yearly_ANT27_1979_2016.nc) is missing and it is not published at https://www.projects.science.uu.nl/iceclimate/publications/data/2018/vwessem2018_tc/RACMO_Yearly/).

Where can I find this data? thank you very much

**Comment by talbrecht** [comment]
Dear @rersnow ,
we do not have control over the data repository, and as the data have no open data license we must not redistribute them. You can write [Melchior Wessem](https://webspace.science.uu.nl/~wesse004/Contact.php) directly. But do you really need evaporation? It is almost 0 over Antarctica and in the [script](https://github.com/pism/pism-ais/blob/master/racmo_wessem/merge_and_rename_variables.py) is is only used, to fill the SMB over the ocean...

**Comment by rersnow** [comment]
Dear talbrecht ，
I'm sorry to reply to you so late because some other things have to be handled. Thank you very much for your help and recovery, I will contact Melchior Wessem to request relevant data.
Thanks again for your help.
I will close this issue later.
