### ISSUE TITLE
Question about input data -velocity

### ISSUE THREAD

**Issue by rersnow** [pism/pism-ais#8]
Hello everyone,
![2021-05-20 15-26-01 ](https://user-images.githubusercontent.com/70734383/118938919-bac00c00-b981-11eb-8514-1e6317e50a4d.png)

I have a question about the input data of the **regional simulation**. Why is **ice velocity** data needed in the **input data** of the regional simulation? The ice velocity is calculated from the ice thickness and topography as the output variable of the simulation results. So what does it **mean** to add ice velocity to the input variable？ 

Thanks in advance for your time.

**Comment by talbrecht** [comment]
Dear @rersnow,
observed ice velocities and ice thickness are prescribed along the (Dirichlet) boundary of the regional setup (`bc_mask`). You could alternatively assume vanishing velocities along a predefined flow divide.

**Comment by rersnow** [comment]
Dear @talbrecht ,
Thanks a lot. Could I simply understand that these observation data are used to delimit the boundary of the research area？

**Comment by talbrecht** [comment]
For regional simulations, you have to define the location of the boundary, but also the boundary conditions (e.g. ice flux (H*U) into the computational domain)..

**Comment by rersnow** [comment]
Okay, I got it. Thank you very much.
