### ISSUE TITLE
InitMIP input data

### ISSUE THREAD

**Issue by rersnow** [pism/pism-ais#9]
When I tried to preprocess the **initMIP** data repeatedly and process the relevant script, it prompted the lack of **input data** (initmip_16km_input.nc). Although I have found the dSMB\dBasalMelt data on https://zenodo.org/record/2651652, but I did not find the input data. 
Could you tell me where you can find this data?

In addition, when I executed the same prepross script, I found that **opttphi_056_initmip4km_nomassoceanconst_amundsenm0p37/snapshots_2450.nc** was needed. What information does this file represent? I have processed most of the previous data and did not find this result. What information does this represent? Where should I get this result?

Thank you for your help!

**Comment by talbrecht** [comment]
Hej @rersnow,
I would suggest to adjust the `initmip_data_path` in the `config.py` to point to your zenodo download folder, and adjust the filenames of `dsmb_file` and `dbmb_file` in the `preprocess.py` script. Variable names schould be the same.

The PISM snapshot file, the preprocessing script is asking for is the `initmip_pism_out` in the `config.py`, that corresponds to `PD_pism_out` in the `preprocess.py` script, provides an equilibrium simulation state with the initial climate forcing, from which we ran **initMIP** experiments, with anomalies added.

Hope that helps?
Torsten

**Comment by talbrecht** [comment]
Hej @rersnow, did it help? Can this issue be closed?

**Comment by rersnow** [comment]
Dear @talbrecht  ,
I'm sorry for not replying to you in time, because I am very anxious about other things these days.

 Thank you very much for your advice and reply, which is very helpful to me. 

Thanks again.I will close this issue later.
